### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by chenjiandongx**
* Update `specs.CPU` to `specs.LinuxCPU`.

The `CPU` Type here has been changed as `specs.LinuxCPU` thus need to update the document.
```golang
// LinuxResources has container runtime resource constraints
type LinuxResources struct {
	CPU *LinuxCPU `json:"cpu,omitempty"`
}
```

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Please sign the commit

**Comment by chenjiandongx** [comment]
@AkihiroSuda like this?

image

**Comment by AkihiroSuda** [comment]
No, DCO sign (`git commit -a -s --amend`)

**Comment by chenjiandongx** [comment]
@AkihiroSuda Have signed now

**Comment by AkihiroSuda** [comment]
Please sign with your real name (Please remove `x`)

**Comment by chenjiandongx** [comment]
@AkihiroSuda done :)

**Pull request merged**
