### PR TITLE
CI: test against Go 1.15

### PR DESCRIPTION
**Pull request by thaJeztah**

### CODE REVIEW

**Comment by estesp** [comment]
Just FYI, we also just merged #173 which solves the `EINTR` issue w/Go 1.14.

**Comment by thaJeztah** [comment]
> Just FYI, we also just merged #173 which solves the EINTR issue w/Go 1.14.

Ah, nice

Should we make that function conditional (so for Go > 1.15 just use ioutil.WriteFile ?)

**Comment by estesp** [comment]
should this be updated to 1.14.7 if we are still considering this?

**Comment by thaJeztah** [comment]
Perhaps best to skip 1.14 and go directly to 1.15; let me update

**Comment by thaJeztah** [comment]
Updated to Go 1.15

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
