### PR TITLE
feat(v2): add Update method for v2.Manager

### PR DESCRIPTION
**Pull request by cathaysia**
Signed-off-by: DragonBillow <DragonBillow@outlook.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
> Signed-off-by: DragonBillow

Please use real name

**Comment by cathaysia** [comment]
Emm, in fact, it's my real name, it's my translated name. I recommit it use my pinyin name. Please check it.

**Review by AkihiroSuda — APPROVED** [review]

**Review by Zyqsempai — APPROVED** [review]
LGTM

**Review by estesp — APPROVED** [review]
LGTM

**Pull request merged**
