### PR TITLE
typo shoulld -> should

### PR DESCRIPTION
**Pull request by Abirdcfly**
Just stumbled upon https://github.com/containerd/cgroups/pull/77/files#r259087886 thanks @mikebrow

Signed-off-by: Abirdcfly <fp544037857@gmail.com>

### CODE REVIEW

**Comment by samuelkarp** [comment]
Would you mind updating your Signed-off-by line to use your real name?  We require that as part of our [contribution policy](https://github.com/containerd/project/blob/main/CONTRIBUTING.md#sign-your-work).

**Comment by Abirdcfly** [comment]
> use your real name

Done. Thanks for you advice.

**Review by estesp — APPROVED** [review]
LGTM

**Review by mikebrow — APPROVED** [review]
LGTM

**Pull request merged**
