### PR TITLE
go.mod: update dependencies

### PR DESCRIPTION
**Pull request by thaJeztah**
### go.mod: github.com/cilium/ebpf v0.2.0

full diff: https://github.com/cilium/ebpf/compare/1c8d4c9ef775...v0.2.0

#### v0.1.0 - Deprecate MapABI and ProgramABI

This release deprecates MapABI and ProgramABI in favour of straight up getters on Map and Program.

#### v0.2.0 - Support LSM hook and add network namespace link

The library now understands lsm/ sections. There is a new link.NetNsLink which allows attaching sk_lookup and flow_dissector programs.

- btf: add go-fuzz targets
- btf: avoid Type copy in FuncProto.walk
- btf: check err in loadSpecFromVmlinux
- btf: handle type name flavours
- CI: test on 5.9 kernel
- cmd/bpf2go: output ELF .o next to the .go file
- link: add AttachSkLookup
- Remove two unused functions
- Support LSM attach
- use buffered I/O to cut down on read syscalls
- Various doc link fixes

### go.mod: github.com/coreos/go-systemd v22.1.0

full diff: https://github.com/coreos/go-systemd/compare/v22.0.0...v22.1.0

- docs: update docs links in README
- unit: do not export private constants
- unit: deserialize keeps all semantic data
- deserialize: Use quote to print possibly-invalid string
- login1: support getting active session and session details

### go.mod: sirupsen/logrus v1.7.0

full diff: https://github.com/sirupsen/logrus/compare/v1.6.0...v1.7.0

removes dependency on github.com/konsorten/go-windows-terminal-sequences

Features:

* a new buffer pool management API has been added
* a set of `<LogLevel>Fn()` functions have been added

### CODE REVIEW

**Review by Zyqsempai — APPROVED** [review]
LGTM(ci failure wasn't caused by this PR)

**Comment by thaJeztah** [comment]
oh! we need to update GH-actions in this repo. Let me do a quick PR for that

**Comment by thaJeztah** [comment]
opened https://github.com/containerd/cgroups/pull/185

**Comment by thaJeztah** [comment]
rebased, now that https://github.com/containerd/cgroups/pull/185 was merged

**Review by estesp — APPROVED** [review]
LGTM

**Pull request merged**
