### PR TITLE
deprecate RunningInUserNS(), migrate to github.com/moby/sys/userns

### PR DESCRIPTION
**Pull request by thaJeztah**
- [x] depends on / stacked on https://github.com/containerd/cgroups/pull/345
- [x] depends on https://github.com/moby/sys/pull/140
- relates to https://github.com/containerd/containerd/pull/10473
- relates to https://github.com/opencontainers/runc/issues/3028

The userns package in libcontainer was integrated into the moby/sys/user module at commit 3778ae603c706494fd1e2c2faf83b406e38d687d.

The userns package is used in many places, and currently either depends on runc/libcontainer, or on containerd, both of which have a complex dependency tree. This patch is part of a series of patches to unify the implementations, and to migrate toward that implementation to simplify the dependency tree.

[3778ae603c706494fd1e2c2faf83b406e38d687d]: https://github.com/opencontainers/runc/commit/3778ae603c706494fd1e2c2faf83b406e38d687d

### CODE REVIEW

**Review by kzys — APPROVED** [review]

**Comment by thaJeztah** [comment]
temporarily moving to draft; pending https://github.com/moby/sys/pull/140#issuecomment-2250644304

**Comment by thaJeztah** [comment]
Okay; updated; this should be good for review again /cc @dmcgowan

**Review by zouyee — APPROVED** [review]

**Comment by thaJeztah** [comment]
@dmcgowan ptal 🤗

**Review by dcantah — APPROVED** [review]

**Review by dims — APPROVED** [review]
LGTM

**Pull request merged**
