### PR TITLE
Added RDMA controller

### PR DESCRIPTION
**Pull request by Zyqsempai**
Related to #104 

Added RDMA controller

Signed-off-by: bpopovschi <zyqsempai@mail.ru>

### CODE REVIEW

**Comment by Zyqsempai** [comment]
@AkihiroSuda @crosbymichael PTAL

**Comment by crosbymichael** [comment]
will need a rebase after all the previous merges

**Comment by Zyqsempai** [comment]
@crosbymichael Done

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
