### PR TITLE
Dereferencing null pointer value.HcaHandles

### PR DESCRIPTION
**Pull request by xuegege5290**
the problem about Dereferencing null pointer value.HcaHandles

### CODE REVIEW

**Review by Zyqsempai — COMMENTED** [review]
Commits still not signed + they should be squashed

**Comment by Zyqsempai** [comment]
@xuegege5290 Squash (git squash or rebase -i) your commits and then sign it `git commit --amend --signoff`

**Review by Zyqsempai — COMMENTED** [review]
Please, take a look at the comments above.

**Comment by xuegege5290** [comment]
> look at the comments above.

I follow your advice ,but it didn`t work ....It was  my first time to pull request.Does it has tutorial easy for newer? I felt frustrated

**Comment by Zyqsempai** [comment]
I recommend following Git docs or tutorials, it's git related only.
Some random articles which could potentially help you.
https://www.internalpointers.com/post/squash-commits-into-one-git
https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits

**Comment by kzys** [comment]
Seems superseded by #218.

**Pull request closed without merging**
