### PR TITLE
Only build for linux

### PR DESCRIPTION
**Pull request by mlaventure**
Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
Isn't it easier to put the import behind a build tag?

**Comment by mlaventure** [comment]
Well, maybe. I initially thought I'd need both linux and windows stats for LCOW, but I haven't looked at the code a bit me, I don't think that'll be necessary in the end. 

I'll know more when I get further ahead in the windows compilation, go-winio is causing me some headaches :)

**Comment by crosbymichael** [comment]
So do you need this PR or no?

**Comment by mlaventure** [comment]
So impatient! :)

Closing it for now, I'll reopen it when I'm sure I do need it.

**Pull request closed without merging**
