### PR TITLE
Switch to ALv2

### LINKED ISSUE #10: Switch license to ALv2
This is part of CNCF now

### PR DESCRIPTION
**Pull request by caniszczyk**
Switch to ALv2 as part of the move to CNCF. Closes #10

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

### CODE REVIEW

**Comment by justincormack** [comment]
You need signoff from all the contributors, the Docker ones will be fine but @ianwoolf needs to agree.

**Comment by crosbymichael** [comment]
Thanks @ianwoolf !

**Comment by ianwoolf** [comment]
Signed-off-by: ian woolf btw515wolf2@gmail.com

**Comment by hqhq** [comment]
LGTM

**Comment by estesp** [comment]
Seems like this can be merged? The CI failure is being fixed under #15

**Comment by crosbymichael** [comment]
sure

**Pull request merged**
